# Generated by Django 2.1.7 on 2019-03-07 06:54

from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190304_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(default=webapp.models.generate_code, max_length=12, unique_for_date='created_date')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Created', 'Создано'), ('Bought', 'Выкуплено'), ('Canceled', 'Отменено')], default='Created', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('disc_started', models.DateTimeField(blank=True, null=True)),
                ('disc_finished', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_on_seat', to='webapp.Seat'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_on_show', to='webapp.Show'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='ticket_discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_discount', to='webapp.Discount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(related_name='booked_seat', to='webapp.Seat'),
        ),
        migrations.AddField(
            model_name='booking',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_show', to='webapp.Show'),
        ),
    ]
