# Generated by Django 2.1.7 on 2019-03-07 07:18

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190307_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='unique_code',
            field=models.CharField(default=webapp.models.generate_code, editable=False, max_length=12, unique_for_date='created_date'),
        ),
    ]
