# Generated by Django 2.1.7 on 2019-03-07 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20190307_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_discount', to='webapp.Discount'),
        ),
    ]
